global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "service-a"
    metrics_path: /metrics
    static_configs:
      - targets: ["service-a:3000"]
  - job_name: "service-b"
    metrics_path: /metrics
    static_configs:
      - targets: ["service-b:3001"]
